### ISSUE TITLE
Don't deprecate Attr.Data

### ISSUE THREAD

**Issue by johannesegger** [dotnet-websharper/html#2]
The html attribute `data` [seems to be deprecated](https://github.com/intellifactory/websharper.html/blob/master/WebSharper.Html.Server/Attributes.fs#L157), but I still use it for showing e.g. a pdf:

```
<object data="path/to/file.pdf" />
```

**Comment by Tarmil** [comment]
Indeed I am not quite sure why it is in `Deprecated`. This module is for attributes that are deprecated by the HTML5 standard, but after looking up, `data` doesn't seem to be one of them. Unfortunately we can't move it to the `Attr` module, since there is already a `Data` function there which is used to create `data-foo` attributes. Not to worry though, even though the module is called `Deprecated` it is not planned for deletion at any point in the future.

**Comment by johannesegger** [comment]
I see, then it's not a problem, thanks for clarification.
