### ISSUE TITLE
Does not compile on C# project (CS0433)

### ISSUE THREAD

**Issue by V0d01ey** [dotnet-websharper/html#5]
How to resolve following build problem?

Error	CS0433	
The type 'Content' exists in both 'WebSharper.Html.Server, Version=4.2.0.0, Culture=neutral, PublicKeyToken=dcd983dec8f76a71' and 'WebSharper.Sitelets, Version=4.2.0.0, Culture=neutral, PublicKeyToken=dcd983dec8f76a71'

**Comment by Tarmil** [comment]
Hi, sorry for replying only now. The `Content` type (F# module, actually) in Html.Server contains the (fairly old) template system for WebSharper.Html. I think the least intrusive way to fix this mixup is to mark it so that the corresponding type is called `ContentModule` in .NET. I'll do it right now.
